# Generated by Django 2.2.5 on 2019-10-23 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=150)),
                ('title_description', models.CharField(blank=True, max_length=100)),
                ('section_description1', models.TextField(blank=True)),
                ('title_section2', models.CharField(blank=True, max_length=100)),
                ('section2_description', models.TextField(blank=True)),
                ('title_section3', models.CharField(blank=True, max_length=100)),
                ('section3_description', models.TextField(blank=True)),
                ('title_section4', models.CharField(blank=True, max_length=100)),
                ('section4_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomePageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('pre_offer', models.CharField(max_length=80)),
                ('button_offer_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DoItTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(blank=True, max_length=100)),
                ('where', models.CharField(blank=True, max_length=50)),
                ('when', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
