# Generated by Django 2.2.5 on 2019-10-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=150)),
                ('title_description', models.CharField(max_length=100)),
                ('section_description1', models.TextField()),
                ('title_section2', models.CharField(max_length=100)),
                ('section2_description', models.TextField()),
                ('title_section3', models.CharField(max_length=100)),
                ('section3_description', models.TextField()),
                ('title_section4', models.CharField(max_length=100)),
                ('section4_description', models.TextField()),
            ],
        ),
    ]
