# Generated by Django 2.2.5 on 2019-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0003_doittable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doittable',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=100)),
        ),
    ]
