# Generated by Django 2.2.5 on 2019-10-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0004_auto_20191024_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doittable',
            name='slug',
        ),
    ]
