# Generated by Django 2.2.5 on 2019-10-24 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doit', '0005_remove_doittable_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoItTable',
            new_name='DoItLine',
        ),
    ]
